/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numa;

import org.junit.Test;
import static org.junit.Assert.*;

// No tests were created for this instance
public class AppTest {
    @Test public void justPass() {
        assertEquals(1,1);
    }
}
